"use strict";
let title = "Project";
console.log(typeof title);
let screens = "Простые, Сложные, Интерактивные";
let screenPrice = 100;
let rollback = 25;
let fullPrice = 1000;
console.log(typeof fullPrice);
let adaptive = true;
console.log(typeof adaptive);
console.log(screens.length);
let cost = "Стоимость верстки экранов ";
let currency = " рублей";
console.log(cost + screenPrice + currency);
let sitePrice = "Стоимость разработки сайта ";
console.log(sitePrice + fullPrice + currency);
let lower = (screens.toLowerCase());
console.log(lower.split(", "));
let cash = "Процент отката посреднику за работу ";
console.log(cash + (fullPrice * (rollback / 100)));